public class Employee {
	String eName; 
    integer eid; 
    String eDept;
    
    public Employee() {
        
    }
    
    public Employee(String name, integer empid, String dept) {
        eid = empId;
        eName = Name;
        eDept = dept;
    }
    
    public string getEmployeeName() {
        return eName;
    }
    
    public integer getEmployeeId() {
        return eid;
    }
    
    public string getEmployeeDept() {
        return eDept;
    }


    
}